### ISSUE TITLE
Question about the RamWrite function.

### ISSUE THREAD

**Issue by MelonSpeedruns** [krikzz/ED64#15]
Hey people. I wasn't able to find a place to ask this question, so I'm making an issue about it. Basically, I saw that the RamWrite function is commented out in CommandProcessor.cs .

I was wondering if I were to add the function as follows, would that allow writing into the RAM while a game is running? 

```
public static byte[] RamWrite(byte[] data, uint startAddress)
        {
            var length = data.Length;

            CommandPacketTransmit(TransmitCommand.RamWrite, startAddress, length, 0);

            UsbInterface.ProgressBarTimerInterval = length > 0x2000000 ? 0x100000 : 0x80000;
            var time = DateTime.Now.Ticks;
            UsbInterface.Write(data);
            time = DateTime.Now.Ticks - time;

            Console.WriteLine($"OK. speed: {GetSpeedString(data.Length, time)}"); //TODO: this should be in the main program! or at least return the time!

            return data;
        }
```

Thanks for your time!

**Comment by networkfusion** [comment]
You might be better off asking on https://discord.gg/WqFgNWf

**Comment by MelonSpeedruns** [comment]
Alright, thank you for the help! I will ask there!

**Comment by networkfusion** [comment]
Also, just an fyi, the ram write function would not work with a retail game as it needs to have usb code inserted into the rom, so its functionality is only available to homebrew.
